### ISSUE TITLE
New layout: centered master

### ISSUE THREAD

**Issue by verajosemanuel** [TyberiusPrime/i3-instant-layout#1]
Love your work. This is very useful.
But I miss one of the layouts I use most: centered master (and stack both sides.)
![D5B49B0F-EB43-4B9D-887D-0FB6D77DAE27](https://user-images.githubusercontent.com/15836677/91432276-c9015180-e861-11ea-9f04-ed28c79a6ae6.jpeg)

**Comment by TyberiusPrime** [comment]
It's in 0.1.5, please upgrade :)
