### ISSUE TITLE
OpenBSD 6.8 xdotool returns error on empty window class on version 0.1.9

### ISSUE THREAD

**Issue by svenknoke** [TyberiusPrime/i3-instant-layout#10]
when invoking i3-instant-layout  [any Layout, eg. vStack]  xdotool returns several errors:
'Failed to compile regex (return code 14): ''  which is caught by the python error trace (see below)

When I change the respective code lines (main.py 57 cont.) from     

    res = subprocess.check_output(
        [
            "xdotool",
            "search",
            "--all",
            "--onlyvisible",
            "--desktop",
            desktop,
            "--class",
            "",
        ]

to 

    res = subprocess.check_output(
        [
            "xdotool",
            "search",
            "--all",
            "--onlyvisible",
            "--desktop",
            desktop,
            "--class",
            "^.*",
        ]

all is fine

When I call xdotool directly with the above parameters and empty string for --class I get the same amount of 'failed to compile regex (return code 14): '' errors.
xdotool returns with valid output if --class is "^.*".

I run OpenBSD 6.8 with all syspatches and the standard GENERIC.MP Kernel
the xdotool version is: 3.20160805.1 an was installed as the regular package (it was not compiled from ports)

Here the errorTrace:

Failed to compile regex (return code 14): ''
Failed to compile regex (return code 14): ''
Failed to compile regex (return code 14): ''
Failed to compile regex (return code 14): ''
Failed to compile regex (return code 14): ''
Failed to compile regex (return code 14): ''
Failed to compile regex (return code 14): ''
Failed to compile regex (return code 14): ''
Failed to compile regex (return code 14): ''
Failed to compile regex (return code 14): ''
Failed to compile regex (return code 14): ''
Failed to compile regex (return code 14): ''
Failed to compile regex (return code 14): ''
Failed to compile regex (return code 14): ''
Failed to compile regex (return code 14): ''
Failed to compile regex (return code 14): ''
Failed to compile regex (return code 14): ''
Failed to compile regex (return code 14): ''
Failed to compile regex (return code 14): ''
Failed to compile regex (return code 14): ''
Failed to compile regex (return code 14): ''
Failed to compile regex (return code 14): ''
Failed to compile regex (return code 14): ''
Failed to compile regex (return code 14): ''
Failed to compile regex (return code 14): ''
Failed to compile regex (return code 14): ''
Traceback (most recent call last):
  File "/home/sknoke/.local/bin/i3-instant-layout", line 11, in <module>
    load_entry_point('i3-instant-layout==0.1.9', 'console_scripts', 'i3-instant-layout')()
  File "/home/sknoke/.local/lib/python3.8/site-packages/i3_instant_layout/main.py", line 229, in main
    apply_layout(layout_class(), "--dry-run" in sys.argv)
  File "/home/sknoke/.local/lib/python3.8/site-packages/i3_instant_layout/main.py", line 89, in apply_layout
    windows = get_window_ids()
  File "/home/sknoke/.local/lib/python3.8/site-packages/i3_instant_layout/main.py", line 57, in get_window_ids
    res = subprocess.check_output(
  File "/usr/local/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/local/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['xdotool', 'search', '--all', '--onlyvisible', '--desktop', '0', '--class', '']' returned non-zero exit status 1.

**Comment by TyberiusPrime** [comment]
The proposed change also works on my linux, just released as 0.1.10.
