### ISSUE TITLE
Command for rofi doesn't work from key bind but works from terminal

### ISSUE THREAD

**Issue by mauromotion** [TyberiusPrime/i3-instant-layout#13]
I'm on Arch Linux.

The command: bindsym $mod+Escape exec "i3-instant-layout --list | rofi -dmenu -i | i3-instant-layout -" works as intended from the terminal but not from the keybinding META + Esc, it gives me an empty dmenu list.

It won't work even if I put the command in a bash script and bind it in the i3 config, same behavior.

I've installed i3-auto-layout with pipx.

Any hints?

**Comment by TyberiusPrime** [comment]
My best crystal ball guess is that there's a difference in $PATH, and it's not finding the command.
Try finding out where the 'binaries' are located with 'which i3-instant-layout', and replacing it with whatever '/<...>/i3-instant-layout' you get back.

**Comment by mauromotion** [comment]
Thanks, your crystal ball worked. I had to point to ~/.local/bin/i3-instant-layout.
