### ISSUE TITLE
i3wm loses workspace layout during/after a lock screen?

### ISSUE THREAD

**Issue by nrvale0** [TyberiusPrime/i3-instant-layout#14]
Thanks for creating this.

I'm having a bit of a hiccup -- I do know some Python -- but before I try to fix it myself am hoping you might be able to provide a bit of guidance. As of Regolith3 (uses i3 as the window manager) I notice that the layouts for non-primary monitors are lost/during after an unlock. Specifically, my non-primary monitors/workspaces are set to 'matrix' and when I unlock the screen they are in the default horizontal layout and have to be set back to matrix.

Any ideas where the core issue might be? Perhaps some problem with newer versions of i3?

**Comment by TyberiusPrime** [comment]
Sorry, I can't be of much help. I've observed similar behavior on occasion with regards to suspend  and multiple screens, and re detecting them being troublesome, and always ended up just writing a python script to drag my workspaces and windows back into something sensible, and tying that to a shortcut :(.

**Comment by nrvale0** [comment]
Thank you. That's still useful information as I've found very little elsewhere on the Internet where others have reported similar. Is there any chance you can share the script you use to reset your displays? I've looked into doing similar Big Hammer approach however I'm relatively new to i3 and have not figured out the "best" way to do this.

**Comment by TyberiusPrime** [comment]
Sure.
It resets the position of the monitors (which was what this particular machine kept forgetting), 
then moves the workspaces back to the right screens.
Check the [i3 list of commands](https://i3wm.org/docs/userguide.html#list_of_commands) for what else you can do. And you have to run this in a python (venv) that has i3ipc installed...


```import time
import subprocess

subprocess.call(
    "xrandr --output HDMI-A-0 --pos 0x1680 --output DisplayPort-0 --primary --rotate right --pos 3840x0",
    shell=True,
)

import i3ipc

i3 = i3ipc.Connection()
focused = i3.get_tree().find_focused()
ws_name = focused.workspace().name
left = (
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "11",
    "12",
    "13",
    "14",
    "15",
    "16",
    "17",
    "18",
    "19",
)
right = ("9", "10")
for ws in i3.get_tree().workspaces():
    if ":" in ws.name:
        short = ws.name[: ws.name.find(":")]
    else:
        short = ws.name
    if short in left:
        print("ws", ws.name, "left", repr(short))
        i3.command(f"workspace {ws.name}")
        i3.command(f"move workspace to output primary")
        i3.command(f"workspace {ws.name}")
        i3.command(f"move workspace to output left")
    elif short in right:
        print("ws", ws.name, "right")
        i3.command(f"workspace {ws.name}")
        i3.command(f"move workspace to output primary")
        i3.command(f"workspace {ws.name}")
    else:
        print(ws.name, "not going there")

print("going back to ", ws_name)
i3.command(f"workspace {ws_name}")
```

**Comment by nrvale0** [comment]
Thanks, again. I'm going to copy that code into my notes for later. I'll go ahead and close this out since it seems as though it must be a bug/limitation of i3 itself.
