### ISSUE TITLE
Getting error, bindkey not showing layout options

### ISSUE THREAD

**Issue by ajP89** [TyberiusPrime/i3-instant-layout#4]
on pressing the bindkey mod+esc I'm not seeing any layout options. On opening from terminal, it gives error `xkbcommon: ERROR: couldn't find a Compose file for locale "en_IN" `. I'm in India and have setup language accordingly.

**Comment by TyberiusPrime** [comment]
Does 'i3-instant-layout --list' work on the terminal? I'd like to see if the error comes from rofi or from i3-instant-layout.

**Comment by ajP89** [comment]
Sorry I'm not proficient enough. I'm getting  i3-instant-layout --list: command not found.  I tried removing rofi from `rofi -dmenu -i` and just `dmenu -i`, it shows dmenu but blank. I guess its a locale.conf file issue

**Comment by TyberiusPrime** [comment]
how have you installed i3-instant-layout? 
Command not found suggests the system can't find i3-instant-layout at all.

**Comment by ajP89** [comment]
i tried to reinstall using `pip install i3-instant-layout`.  It gives `Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: i3-instant-layout in ./.local/lib/python3.8/site-packages (0.1.6)`

**Comment by ajP89** [comment]
Oh.. I tried `sudo pip install i3-instant-layout`. It works perfectly now. 
Thanks for this gem.
